---
  - hosts: all
    become: true
    tasks:
      - name: Upgrade packages
        apt: 
          upgrade: full
#You might not want to have this on production
      - name: Clean packages
        apt:
          autoremove: yes
